export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIES_LOADING = "GET_MOVIES_LOADING";
export const GET_MOVIES_ERROR = "GET_MOVIES_ERROR";

//Movie
export const EDIT_MOVIE = "EDIT_MOVIE";
export const EDIT_MOVIE_LOADING = "EDIT_MOVIE_LOADING";
export const EDIT_MOVIE_ERROR = "EDIT_MOVIE_ERROR";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const DELETE_MOVIE_LOADING = "DELETE_MOVIE_LOADING";
export const DELETE_MOVIE_ERROR = "DELETE_MOVIE_ERROR";
export const ADD_MOVIE = "ADD_MOVIE";
export const ADD_MOVIE_LOADING = "ADD_MOVIE_LOADING";
export const ADD_MOVIE_ERROR = "ADD_MOVIE_ERROR";
export const GET_MOVIE = "GET_MOVIE";
export const GET_MOVIE_LOADING = "GET_MOVIE_LOADING";
export const GET_MOVIE_ERROR = "GET_MOVIE_ERROR";
